# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_copytree.ipynb.

# %% auto 0
__all__ = ['copytree_agnostic']

# %% ../nbs/01_copytree.ipynb 2
import sys
from shutil import copytree

# %% ../nbs/01_copytree.ipynb 4
def copytree_agnostic(a,b):
    if sys.version_info.major >=3 and sys.version_info.minor >=8: copytree(a, b, dirs_exist_ok=True)
    else:
        from distutils.dir_util import copy_tree
        copy_tree(a, b)
