# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb 3
from shutil import copytree
from pathlib import Path

# %% ../nbs/00_core.ipynb 4
def foo(): pass
