# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['src', 'dest']

# %% ../nbs/00_core.ipynb 3
from fastcore.all import in_ipython
import nbdev.config
from . import copytree
from pathlib import Path

# %% ../nbs/00_core.ipynb 4
if in_ipython():
    copy_root_dir = Path(copytree.__file__).parents[1] 
else:
    copy_root_dir = Path(__file__).parents[1]

# %% ../nbs/00_core.ipynb 6
src = Path(copy_root_dir) / "assets"
dest = Path().cwd() / "output"

# %% ../nbs/00_core.ipynb 7
copytree.copytree_agnostic(src, dest)
