# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['src', 'dest']

# %% ../nbs/00_core.ipynb 3
from shutil import copytree
from pathlib import Path

# %% ../nbs/00_core.ipynb 6
src = Path(__file__).parents[1] / "assets"
dest = Path().cwd() / "output"

# %% ../nbs/00_core.ipynb 7
copytree(src, dest, dirs_exist_ok=True)
